import Head from "next/head";
import Image from "next/image";
import Hero from "./components/Hero";
import Navbar from "./components/Navbar";
import Service from "./components/Service";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="max-w-[1920]">
        <Navbar />
      </header>
      <main className="px-8">
        <Hero />
        <Service/>
      </main>
    </div>
  );
}
